language: en
pipeline:
- name: WhitespaceTokenizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
- name: EmbeddingIntentClassifier
  intent_tokenization_flag: true
  intent_split_symbol: +
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
